/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20TokenSol from "./ERC20Token.sol";
export type { erc20TokenSol };
export type { Token } from "./Token";
export * as factories from "./factories";
export type { ERC20 } from "./ERC20Token.sol/ERC20";
export { ERC20__factory } from "./factories/ERC20Token.sol/ERC20__factory";
export type { IERC20 } from "./ERC20Token.sol/IERC20";
export { IERC20__factory } from "./factories/ERC20Token.sol/IERC20__factory";
export { Token__factory } from "./factories/Token__factory";
